[tool.poetry]
name = "30days-training"
version = "0.1.0"
description = ""
authors = ["istyle-osadam <osadam@istyle.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
